spring.application.name=Create-Task-Application
server.port=8081
spring.datasource.url= jdbc:postgresql://localhost:5432/TaskManagementDatabase
spring.datasource.username=postgres
spring.datasource.password=root
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
